server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/application?characterEncoding=utf-8&useSSL=true
    username: Li
    password: KWa-eWhjCa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true